IF db_id('MAJSTERKLEPKA') IS NULL
CREATE DATABASE MAJSTERKLEPKA;

GO

USE MAJSTERKLEPKA;

IF EXISTS (SELECT *FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME='PRODUKTY' AND TABLE_SCHEMA = 'dbo')
DROP TABLE dbo.PRODUKTY;

IF EXISTS (SELECT *FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME='ZAMOWIENIA' AND TABLE_SCHEMA = 'dbo')
DROP TABLE dbo.ZAMOWIENIA;

IF EXISTS (SELECT *FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME='ZAMOWIENIE_SZ' AND TABLE_SCHEMA = 'dbo')
DROP TABLE dbo.ZAMOWIENIE_SZ;

IF EXISTS (SELECT *FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME='DOSTAWCY' AND TABLE_SCHEMA = 'dbo')
DROP TABLE dbo.DOSTAWCY;

IF EXISTS (SELECT *FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME='KATEGORIA' AND TABLE_SCHEMA = 'dbo')
DROP TABLE dbo.KATEGORIA;

IF EXISTS (SELECT *FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME='KLIENCI' AND TABLE_SCHEMA = 'dbo')
DROP TABLE dbo.KLIENCI;

IF EXISTS (SELECT *FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME='PRACOWNICY' AND TABLE_SCHEMA = 'dbo')
DROP TABLE dbo.PRACOWNICY;

CREATE TABLE PRODUKTY 
(
ID_PRODUKT INT IDENTITY NOT NULL,
ID_DOSTAWCA VARCHAR(5),
ID_KATEGORIA VARCHAR(5),
NAZWA_PRODUKTU VARCHAR(100),
STAN INT,
CENA_NETTO INT,
CENA_BRUTTO INT,
INFORMACJE VARCHAR(250),
GWARANCJA INT  

PRIMARY KEY (ID_PRODUKT)
)

CREATE TABLE ZAMOWIENIA 
(
ID_ZAMOWIENIE INT IDENTITY UNIQUE NOT NULL,
ID_KLIENT INT,
ID_PRACOWNIK VARCHAR (5),
CZAS DATE,
FAKTURA BIT

PRIMARY KEY (ID_ZAMOWIENIE) 
)

CREATE TABLE ZAMOWIENIE_SZ (
ID_ZAMOWIENIE INT IDENTITY(1,1) NOT NULL,
ID_PRODUKT INT,
ILOSC INT 

PRIMARY KEY (ID_ZAMOWIENIE) 
)

CREATE TABLE DOSTAWCY (
ID_DOSTAWCA VARCHAR (5) NOT NULL,
NAZWA_FIRMY VARCHAR(20),
ADRES VARCHAR(30),
MIASTO VARCHAR(20),
KOD VARCHAR(10),
KRAJ VARCHAR(20),
TELEFON INT 

PRIMARY KEY (ID_DOSTAWCA)
)

CREATE TABLE KATEGORIA (
ID_KATEGORIA VARCHAR(5) NOT NULL,
NAZWA_KATEGORII VARCHAR(20),

PRIMARY KEY (ID_KATEGORIA)
)

CREATE TABLE KLIENCI (
ID_KLIENT INT IDENTITY NOT NULL,
NAZWA VARCHAR (50),
KONTAKT INT 

PRIMARY KEY (ID_KLIENT)
)

CREATE TABLE PRACOWNICY (
ID_PRACOWNIK VARCHAR (5) NOT NULL,
STANOWISKO VARCHAR(20) 

PRIMARY KEY (ID_PRACOWNIK)
)

ALTER TABLE PRODUKTY
ADD CONSTRAINT PRODUKTY_KATEGORIA_FK 
FOREIGN KEY (ID_KATEGORIA) REFERENCES dbo.KATEGORIA(ID_KATEGORIA)

ALTER TABLE ZAMOWIENIE_SZ
ADD CONSTRAINT PRODUKTY_ZAMOWIENIA_FK 
FOREIGN KEY (ID_PRODUKT) REFERENCES dbo.PRODUKTY(ID_PRODUKT)

ALTER TABLE PRODUKTY
ADD CONSTRAINT PRODUKTY_DOSTAWCY_FK 
FOREIGN KEY (ID_DOSTAWCA) REFERENCES dbo.DOSTAWCY(ID_DOSTAWCA)

ALTER TABLE ZAMOWIENIA
ADD CONSTRAINT ZAMOWIENIA_KLIENT_FK 
FOREIGN KEY (ID_KLIENT) REFERENCES dbo.KLIENCI(ID_KLIENT)

ALTER TABLE ZAMOWIENIA
ADD CONSTRAINT ZAMOWIENIA_ID_FK 
FOREIGN KEY (ID_ZAMOWIENIE) REFERENCES dbo.ZAMOWIENIE_SZ(ID_ZAMOWIENIE)

ALTER TABLE ZAMOWIENIA
ADD CONSTRAINT ZAMOWIENIA_PRACOWNIK_FK 
FOREIGN KEY (ID_PRACOWNIK) REFERENCES dbo.PRACOWNICY(ID_PRACOWNIK)
