USE MAJSTERKLEPKA

BULK
INSERT dbo.DOSTAWCY
FROM 'C:\Users\Ziemek\Desktop\BDII\DANE\DOSTAWCY.csv'
WITH
(
FIRSTROW = 2,
FIELDTERMINATOR = ';',
ROWTERMINATOR = '\n'
);

BULK
INSERT dbo.KATEGORIA
FROM 'C:\Users\Ziemek\Desktop\BDII\DANE\KATEGORIA.csv'
WITH
(
FIRSTROW = 2,
FIELDTERMINATOR = ';',
ROWTERMINATOR = '\n'
);

BULK
INSERT dbo.KLIENCI
FROM 'C:\Users\Ziemek\Desktop\BDII\DANE\KLIENCI.csv'
WITH
(
FIRSTROW = 2,
FIELDTERMINATOR = ';',
ROWTERMINATOR = '\n'
);

BULK
INSERT dbo.PRACOWNICY
FROM 'C:\Users\Ziemek\Desktop\BDII\DANE\PRACOWNICY.csv'
WITH
(
FIRSTROW = 2,
FIELDTERMINATOR = ';',
ROWTERMINATOR = '\n'
);

BULK
INSERT dbo.PRODUKTY
FROM 'C:\Users\Ziemek\Desktop\BDII\DANE\PRODUKTY.csv'
WITH
(
FIRSTROW = 2,
FIELDTERMINATOR = ';',
ROWTERMINATOR = '\n'
);

BULK
INSERT dbo.ZAMOWIENIA
FROM 'C:\Users\Ziemek\Desktop\BDII\DANE\ZAMOWIENIA.csv'
WITH
(
FIRSTROW = 2,
FIELDTERMINATOR = ';',
ROWTERMINATOR = '\n'
);

BULK
INSERT dbo.ZAMOWIENIE_SZ
FROM 'C:\Users\Ziemek\Desktop\BDII\DANE\ZAMOWIENIE_SZ.csv'
WITH
(
FIRSTROW = 2,
FIELDTERMINATOR = ';',
ROWTERMINATOR = '\n'
);