USE [MAJSTERKLEPKA]
GO
CREATE SCHEMA [db_kasjer] AUTHORIZATION dbo
GO

USE [MAJSTERKLEPKA]
GO
CREATE ROLE [db_kasjer] AUTHORIZATION dbo
GO

USE [MAJSTERKLEPKA]
GO
ALTER AUTHORIZATION ON SCHEMA::db_kasjer TO [db_kasjer]
GO

USE [MAJSTERKLEPKA]
--ALL, ALTER, CONTROL, DELETE, EXECUTE, INSERT, UPDATE, VIEW DEFINITION...
GO
GRANT SELECT ON [dbo.PRODUKTY]  TO [db_kasjer]
GRANT SELECT ON [dbo.ZAMOWIENIA] TO [db_kasjer]
GRANT SELECT ON [dbo.ZAMOWIENIA_SZ] TO [db_kasjer]
GRANT ALL ON [dbo.KLIENCI]  TO [db_kasjer]
GRANT SELECT ON [dbo.DOSTAWCY]  TO [db_kasjer]
GO

USE [MAJSTERKLEPKA]
GO
GRANT UPDATE ON [dbo.ZAMOWIENIA] TO [db_kasjer]
GRANT UPDATE ON [dbo.ZAMOWIENIA_SZ] TO [db_kasjer]
GRANT UPDATE ON [dbo.KLIENCI]  TO [db_kasjer]
GO

USE [MAJSTERKLEPKA]
GO
GRANT VIEW DEFINITION ON [dbo.PRODUKTY]  TO [db_kasjer]
GRANT VIEW DEFINITION ON [dbo.ZAMOWIENIA] TO [db_kasjer]
GRANT VIEW DEFINITION ON [dbo.ZAMOWIENIA_SZ] TO [db_kasjer]
GRANT VIEW DEFINITION ON [dbo.KLIENCI]  TO [db_kasjer]
GRANT VIEW DEFINITION ON [dbo.DOSTAWCY]  TO [db_kasjer]
GO

USE [MAJSTERKLEPKA]
GO
DENY ALL ON [dbo.PRACOWNICY]  TO [db_kasjer]
GO